"""empty message

Revision ID: 4217874c36da
Revises: bbc1527df16d
Create Date: 2017-12-31 19:38:55.920142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4217874c36da'
down_revision = 'bbc1527df16d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('lastName', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('locationId', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('phoneNumber', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('registeredOn', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'user', 'location', ['locationId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'registeredOn')
    op.drop_column('user', 'phoneNumber')
    op.drop_column('user', 'locationId')
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
