"""empty message

Revision ID: b431043ff42f
Revises: 3bf42ec07a8e
Create Date: 2018-07-29 17:11:03.834044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b431043ff42f'
down_revision = '3bf42ec07a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('postalCode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('location', 'postalCode')
    # ### end Alembic commands ###
